### PR TITLE
v13.13.0 

### PR DESCRIPTION
**Pull request by fproldan**
- Account number and name incorrectly imported using COA importer
- Multiple fixes to timesheets
- Totals row incorrect value in GL Entry
- Sales Order delivery Date not getting set via data import 
- Add cost center in gl entry for advance payment entry
- Item Variant selection empty popup on website
- Improve performance of fetching account balance in chart of accounts 
- Chart Of Accounts import button not visible
- Website Items with same Item name unhandled, thumbnails missing
- Delete linked Transaction Deletion Record docs on deleting company
- Display appropriate message for Payment Term discrepancies in Payment Entry 
- Fixed variant qty in BOM while making work order
- Consolidated report not consider company currency
- Batch Number not copied from Purchase Receipt to Stock Entry

### CODE REVIEW

**Comment by ValentinaPruvost** [comment]
@fproldan mergié esto sin fijarme si estaban los labels de backport 🤦🏻‍♀️

**Comment by fproldan** [comment]
@ValentinaPruvost  se me re pasaron a mi tmb.

**Comment by ValentinaPruvost** [comment]
@fproldan esto... no termino de entender si le faltan los backports o ya están mergeados...

**Comment by fproldan** [comment]
@ValentinaPruvost ahi estan los backports

**Pull request merged**
