### PR TITLE
[Backport staging] Sitio web fixed (#43)

### PR DESCRIPTION
**Pull request by fproldan**
https://github.com/fproldan/erpnext/pull/43

* fix: web form

* fix: web form

* feat: website

* feat: improvement

* feat: fixtures

* feat: fixtures

* feat: fixtures

* feat: domains

* feat: rename web templates

* fix: typos

* fix: typos

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

### CODE REVIEW

**Comment by ValentinaPruvost** [comment]
@fproldan

**Comment by fproldan** [comment]
@ValentinaPruvost ✔️

**Comment by ValentinaPruvost** [comment]
@fproldan

**Comment by fproldan** [comment]
@ValentinaPruvost

**Pull request merged**
