### PR TITLE
[Backport diamoerp-staging] feat: Payment Terms Status report (backport #29137)

### PR DESCRIPTION
**Pull request by fproldan**
https://github.com/fproldan/erpnext/pull/412

### CODE REVIEW

**Comment by ValentinaPruvost** [comment]
@fproldan acá hay un conflicto

**Comment by fproldan** [comment]
✅

**Comment by ValentinaPruvost** [comment]
@fproldan quedó un conflicto

**Comment by fproldan** [comment]
✅

**Pull request merged**
